/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMajorityVoting__factory } from "./IMajorityVoting__factory";
export { MajorityVotingBase__factory } from "./MajorityVotingBase__factory";
