/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AddresslistVotingSetup } from "./AddresslistVotingSetup";
export type { GroupVotingSetup } from "./GroupVotingSetup";
