/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GroupVoting__factory } from "./GroupVoting__factory";
export { GroupVotingList__factory } from "./GroupVotingList__factory";
export { GroupVotingSetup__factory } from "./GroupVotingSetup__factory";
export { Vault__factory } from "./Vault__factory";
