/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface CallbackHandlerInterface extends utils.Interface {
  functions: {};

  events: {
    "CallbackReceived(address,bytes4,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CallbackReceived"): EventFragment;
}

export interface CallbackReceivedEventObject {
  sender: string;
  sig: string;
  data: string;
}
export type CallbackReceivedEvent = TypedEvent<
  [string, string, string],
  CallbackReceivedEventObject
>;

export type CallbackReceivedEventFilter =
  TypedEventFilter<CallbackReceivedEvent>;

export interface CallbackHandler extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CallbackHandlerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "CallbackReceived(address,bytes4,bytes)"(
      sender?: null,
      sig?: PromiseOrValue<BytesLike> | null,
      data?: null
    ): CallbackReceivedEventFilter;
    CallbackReceived(
      sender?: null,
      sig?: PromiseOrValue<BytesLike> | null,
      data?: null
    ): CallbackReceivedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
