/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governance from "./governance";
export type { governance };
import type * as utils from "./utils";
export type { utils };
