/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AddresslistVotingSetup__factory } from "./AddresslistVotingSetup__factory";
export { GroupVotingSetup__factory } from "./GroupVotingSetup__factory";
