/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export declare namespace IDAO {
  export type ActionStruct = {
    to: PromiseOrValue<string>;
    value: PromiseOrValue<BigNumberish>;
    data: PromiseOrValue<BytesLike>;
  };

  export type ActionStructOutput = [string, BigNumber, string] & {
    to: string;
    value: BigNumber;
    data: string;
  };
}

export interface IDAOInterface extends utils.Interface {
  functions: {
    "deposit(address,uint256,string)": FunctionFragment;
    "execute(bytes32,(address,uint256,bytes)[],uint256)": FunctionFragment;
    "getTrustedForwarder()": FunctionFragment;
    "hasPermission(address,address,bytes32,bytes)": FunctionFragment;
    "isValidSignature(bytes32,bytes)": FunctionFragment;
    "registerStandardCallback(bytes4,bytes4,bytes4)": FunctionFragment;
    "setMetadata(bytes)": FunctionFragment;
    "setSignatureValidator(address)": FunctionFragment;
    "setTrustedForwarder(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "deposit"
      | "execute"
      | "getTrustedForwarder"
      | "hasPermission"
      | "isValidSignature"
      | "registerStandardCallback"
      | "setMetadata"
      | "setSignatureValidator"
      | "setTrustedForwarder"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [
      PromiseOrValue<BytesLike>,
      IDAO.ActionStruct[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustedForwarder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasPermission",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerStandardCallback",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setMetadata",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setSignatureValidator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedForwarder",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerStandardCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSignatureValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedForwarder",
    data: BytesLike
  ): Result;

  events: {
    "Deposited(address,address,uint256,string)": EventFragment;
    "Executed(address,bytes32,tuple[],uint256,bytes[])": EventFragment;
    "MetadataSet(bytes)": EventFragment;
    "NativeTokenDeposited(address,uint256)": EventFragment;
    "SignatureValidatorSet(address)": EventFragment;
    "StandardCallbackRegistered(bytes4,bytes4,bytes4)": EventFragment;
    "TrustedForwarderSet(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Deposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Executed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MetadataSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NativeTokenDeposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SignatureValidatorSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StandardCallbackRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TrustedForwarderSet"): EventFragment;
}

export interface DepositedEventObject {
  sender: string;
  token: string;
  amount: BigNumber;
  _reference: string;
}
export type DepositedEvent = TypedEvent<
  [string, string, BigNumber, string],
  DepositedEventObject
>;

export type DepositedEventFilter = TypedEventFilter<DepositedEvent>;

export interface ExecutedEventObject {
  actor: string;
  callId: string;
  actions: IDAO.ActionStructOutput[];
  failureMap: BigNumber;
  execResults: string[];
}
export type ExecutedEvent = TypedEvent<
  [string, string, IDAO.ActionStructOutput[], BigNumber, string[]],
  ExecutedEventObject
>;

export type ExecutedEventFilter = TypedEventFilter<ExecutedEvent>;

export interface MetadataSetEventObject {
  metadata: string;
}
export type MetadataSetEvent = TypedEvent<[string], MetadataSetEventObject>;

export type MetadataSetEventFilter = TypedEventFilter<MetadataSetEvent>;

export interface NativeTokenDepositedEventObject {
  sender: string;
  amount: BigNumber;
}
export type NativeTokenDepositedEvent = TypedEvent<
  [string, BigNumber],
  NativeTokenDepositedEventObject
>;

export type NativeTokenDepositedEventFilter =
  TypedEventFilter<NativeTokenDepositedEvent>;

export interface SignatureValidatorSetEventObject {
  signatureValidator: string;
}
export type SignatureValidatorSetEvent = TypedEvent<
  [string],
  SignatureValidatorSetEventObject
>;

export type SignatureValidatorSetEventFilter =
  TypedEventFilter<SignatureValidatorSetEvent>;

export interface StandardCallbackRegisteredEventObject {
  interfaceId: string;
  callbackSelector: string;
  magicNumber: string;
}
export type StandardCallbackRegisteredEvent = TypedEvent<
  [string, string, string],
  StandardCallbackRegisteredEventObject
>;

export type StandardCallbackRegisteredEventFilter =
  TypedEventFilter<StandardCallbackRegisteredEvent>;

export interface TrustedForwarderSetEventObject {
  forwarder: string;
}
export type TrustedForwarderSetEvent = TypedEvent<
  [string],
  TrustedForwarderSetEventObject
>;

export type TrustedForwarderSetEventFilter =
  TypedEventFilter<TrustedForwarderSetEvent>;

export interface IDAO extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDAOInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deposit(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _reference: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    execute(
      _callId: PromiseOrValue<BytesLike>,
      _actions: IDAO.ActionStruct[],
      _allowFailureMap: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getTrustedForwarder(overrides?: CallOverrides): Promise<[string]>;

    hasPermission(
      _where: PromiseOrValue<string>,
      _who: PromiseOrValue<string>,
      _permissionId: PromiseOrValue<BytesLike>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isValidSignature(
      _hash: PromiseOrValue<BytesLike>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerStandardCallback(
      _interfaceId: PromiseOrValue<BytesLike>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      _magicNumber: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMetadata(
      _metadata: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setSignatureValidator(
      _signatureValidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTrustedForwarder(
      _trustedForwarder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  deposit(
    _token: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    _reference: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  execute(
    _callId: PromiseOrValue<BytesLike>,
    _actions: IDAO.ActionStruct[],
    _allowFailureMap: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getTrustedForwarder(overrides?: CallOverrides): Promise<string>;

  hasPermission(
    _where: PromiseOrValue<string>,
    _who: PromiseOrValue<string>,
    _permissionId: PromiseOrValue<BytesLike>,
    _data: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isValidSignature(
    _hash: PromiseOrValue<BytesLike>,
    _signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerStandardCallback(
    _interfaceId: PromiseOrValue<BytesLike>,
    _callbackSelector: PromiseOrValue<BytesLike>,
    _magicNumber: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMetadata(
    _metadata: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setSignatureValidator(
    _signatureValidator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTrustedForwarder(
    _trustedForwarder: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deposit(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _reference: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    execute(
      _callId: PromiseOrValue<BytesLike>,
      _actions: IDAO.ActionStruct[],
      _allowFailureMap: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[], BigNumber]>;

    getTrustedForwarder(overrides?: CallOverrides): Promise<string>;

    hasPermission(
      _where: PromiseOrValue<string>,
      _who: PromiseOrValue<string>,
      _permissionId: PromiseOrValue<BytesLike>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isValidSignature(
      _hash: PromiseOrValue<BytesLike>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    registerStandardCallback(
      _interfaceId: PromiseOrValue<BytesLike>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      _magicNumber: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMetadata(
      _metadata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setSignatureValidator(
      _signatureValidator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setTrustedForwarder(
      _trustedForwarder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Deposited(address,address,uint256,string)"(
      sender?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: null,
      _reference?: null
    ): DepositedEventFilter;
    Deposited(
      sender?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: null,
      _reference?: null
    ): DepositedEventFilter;

    "Executed(address,bytes32,tuple[],uint256,bytes[])"(
      actor?: PromiseOrValue<string> | null,
      callId?: null,
      actions?: null,
      failureMap?: null,
      execResults?: null
    ): ExecutedEventFilter;
    Executed(
      actor?: PromiseOrValue<string> | null,
      callId?: null,
      actions?: null,
      failureMap?: null,
      execResults?: null
    ): ExecutedEventFilter;

    "MetadataSet(bytes)"(metadata?: null): MetadataSetEventFilter;
    MetadataSet(metadata?: null): MetadataSetEventFilter;

    "NativeTokenDeposited(address,uint256)"(
      sender?: null,
      amount?: null
    ): NativeTokenDepositedEventFilter;
    NativeTokenDeposited(
      sender?: null,
      amount?: null
    ): NativeTokenDepositedEventFilter;

    "SignatureValidatorSet(address)"(
      signatureValidator?: null
    ): SignatureValidatorSetEventFilter;
    SignatureValidatorSet(
      signatureValidator?: null
    ): SignatureValidatorSetEventFilter;

    "StandardCallbackRegistered(bytes4,bytes4,bytes4)"(
      interfaceId?: null,
      callbackSelector?: null,
      magicNumber?: null
    ): StandardCallbackRegisteredEventFilter;
    StandardCallbackRegistered(
      interfaceId?: null,
      callbackSelector?: null,
      magicNumber?: null
    ): StandardCallbackRegisteredEventFilter;

    "TrustedForwarderSet(address)"(
      forwarder?: null
    ): TrustedForwarderSetEventFilter;
    TrustedForwarderSet(forwarder?: null): TrustedForwarderSetEventFilter;
  };

  estimateGas: {
    deposit(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _reference: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    execute(
      _callId: PromiseOrValue<BytesLike>,
      _actions: IDAO.ActionStruct[],
      _allowFailureMap: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getTrustedForwarder(overrides?: CallOverrides): Promise<BigNumber>;

    hasPermission(
      _where: PromiseOrValue<string>,
      _who: PromiseOrValue<string>,
      _permissionId: PromiseOrValue<BytesLike>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidSignature(
      _hash: PromiseOrValue<BytesLike>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerStandardCallback(
      _interfaceId: PromiseOrValue<BytesLike>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      _magicNumber: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMetadata(
      _metadata: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setSignatureValidator(
      _signatureValidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTrustedForwarder(
      _trustedForwarder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deposit(
      _token: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _reference: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    execute(
      _callId: PromiseOrValue<BytesLike>,
      _actions: IDAO.ActionStruct[],
      _allowFailureMap: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getTrustedForwarder(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasPermission(
      _where: PromiseOrValue<string>,
      _who: PromiseOrValue<string>,
      _permissionId: PromiseOrValue<BytesLike>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidSignature(
      _hash: PromiseOrValue<BytesLike>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerStandardCallback(
      _interfaceId: PromiseOrValue<BytesLike>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      _magicNumber: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMetadata(
      _metadata: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setSignatureValidator(
      _signatureValidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTrustedForwarder(
      _trustedForwarder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
