/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  DaoAuthorizableUpgradeable,
  DaoAuthorizableUpgradeableInterface,
} from "../../../../../../@aragon/osx/core/plugin/dao-authorizable/DaoAuthorizableUpgradeable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [],
    name: "dao",
    outputs: [
      {
        internalType: "contract IDAO",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class DaoAuthorizableUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): DaoAuthorizableUpgradeableInterface {
    return new utils.Interface(_abi) as DaoAuthorizableUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DaoAuthorizableUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DaoAuthorizableUpgradeable;
  }
}
