/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daoAuthorizable from "./dao-authorizable";
export type { daoAuthorizable };
import type * as membership from "./membership";
export type { membership };
import type * as proposal from "./proposal";
export type { proposal };
export type { IPlugin } from "./IPlugin";
export type { PluginUUPSUpgradeable } from "./PluginUUPSUpgradeable";
