/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  PermissionManager,
  PermissionManagerInterface,
} from "../../../../../@aragon/osx/core/permission/PermissionManager";

const _abi = [
  {
    inputs: [],
    name: "AnyAddressDisallowedForWhoAndWhere",
    type: "error",
  },
  {
    inputs: [],
    name: "ConditionNotPresentForAnyAddress",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "where",
        type: "address",
      },
      {
        internalType: "address",
        name: "who",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "permissionId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "currentCondition",
        type: "address",
      },
      {
        internalType: "address",
        name: "newCondition",
        type: "address",
      },
    ],
    name: "PermissionAlreadyGrantedForDifferentCondition",
    type: "error",
  },
  {
    inputs: [],
    name: "PermissionsForAnyAddressDisallowed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "where",
        type: "address",
      },
      {
        internalType: "address",
        name: "who",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "permissionId",
        type: "bytes32",
      },
    ],
    name: "Unauthorized",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "permissionId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "here",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "where",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "who",
        type: "address",
      },
      {
        indexed: false,
        internalType: "contract IPermissionCondition",
        name: "condition",
        type: "address",
      },
    ],
    name: "Granted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "permissionId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "here",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "where",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "who",
        type: "address",
      },
    ],
    name: "Revoked",
    type: "event",
  },
  {
    inputs: [],
    name: "ROOT_PERMISSION_ID",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "enum PermissionLib.Operation",
            name: "operation",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "where",
            type: "address",
          },
          {
            internalType: "address",
            name: "who",
            type: "address",
          },
          {
            internalType: "address",
            name: "condition",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "permissionId",
            type: "bytes32",
          },
        ],
        internalType: "struct PermissionLib.MultiTargetPermission[]",
        name: "_items",
        type: "tuple[]",
      },
    ],
    name: "applyMultiTargetPermissions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_where",
        type: "address",
      },
      {
        components: [
          {
            internalType: "enum PermissionLib.Operation",
            name: "operation",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "who",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "permissionId",
            type: "bytes32",
          },
        ],
        internalType: "struct PermissionLib.SingleTargetPermission[]",
        name: "items",
        type: "tuple[]",
      },
    ],
    name: "applySingleTargetPermissions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_where",
        type: "address",
      },
      {
        internalType: "address",
        name: "_who",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "_permissionId",
        type: "bytes32",
      },
    ],
    name: "grant",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_where",
        type: "address",
      },
      {
        internalType: "address",
        name: "_who",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "_permissionId",
        type: "bytes32",
      },
      {
        internalType: "contract IPermissionCondition",
        name: "_condition",
        type: "address",
      },
    ],
    name: "grantWithCondition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_where",
        type: "address",
      },
      {
        internalType: "address",
        name: "_who",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "_permissionId",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "isGranted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_where",
        type: "address",
      },
      {
        internalType: "address",
        name: "_who",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "_permissionId",
        type: "bytes32",
      },
    ],
    name: "revoke",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class PermissionManager__factory {
  static readonly abi = _abi;
  static createInterface(): PermissionManagerInterface {
    return new utils.Interface(_abi) as PermissionManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PermissionManager {
    return new Contract(address, _abi, signerOrProvider) as PermissionManager;
  }
}
