/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GroupVoting } from "./GroupVoting";
export type { GroupVotingList } from "./GroupVotingList";
export type { GroupVotingSetup } from "./GroupVotingSetup";
export type { Vault } from "./Vault";
