/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as groupVotingSol from "./GroupVoting.sol";
export * as groupVotingSetupSol from "./GroupVotingSetup.sol";
