/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dao from "./dao";
export type { dao };
import type * as permission from "./permission";
export type { permission };
import type * as plugin from "./plugin";
export type { plugin };
import type * as utils from "./utils";
export type { utils };
