/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPermissionCondition } from "./IPermissionCondition";
export type { PermissionLib } from "./PermissionLib";
export type { PermissionManager } from "./PermissionManager";
