/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IProposal__factory } from "./IProposal__factory";
export { ProposalUpgradeable__factory } from "./ProposalUpgradeable__factory";
