/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AddresslistVoting__factory } from "./AddresslistVoting__factory";
export { GroupVoting__factory } from "./GroupVoting__factory";
