/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPlugin,
  IPluginInterface,
} from "../../../../../@aragon/osx/core/plugin/IPlugin";

const _abi = [
  {
    inputs: [],
    name: "pluginType",
    outputs: [
      {
        internalType: "enum IPlugin.PluginType",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPlugin__factory {
  static readonly abi = _abi;
  static createInterface(): IPluginInterface {
    return new utils.Interface(_abi) as IPluginInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPlugin {
    return new Contract(address, _abi, signerOrProvider) as IPlugin;
  }
}
