/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as groupVotingPlugin from "./GroupVotingPlugin";
export type { groupVotingPlugin };
import type * as swapTokenPlugin from "./SwapTokenPlugin";
export type { swapTokenPlugin };
