/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMajorityVoting } from "./IMajorityVoting";
export type { MajorityVotingBase } from "./MajorityVotingBase";
