/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DAO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DAO__factory>;
    getContractFactory(
      name: "IDAO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDAO__factory>;
    getContractFactory(
      name: "IEIP4824",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IEIP4824__factory>;
    getContractFactory(
      name: "IPermissionCondition",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPermissionCondition__factory>;
    getContractFactory(
      name: "PermissionLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PermissionLib__factory>;
    getContractFactory(
      name: "PermissionManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PermissionManager__factory>;
    getContractFactory(
      name: "DaoAuthorizableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DaoAuthorizableUpgradeable__factory>;
    getContractFactory(
      name: "IPlugin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPlugin__factory>;
    getContractFactory(
      name: "IMembership",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMembership__factory>;
    getContractFactory(
      name: "PluginUUPSUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PluginUUPSUpgradeable__factory>;
    getContractFactory(
      name: "IProposal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IProposal__factory>;
    getContractFactory(
      name: "ProposalUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProposalUpgradeable__factory>;
    getContractFactory(
      name: "CallbackHandler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CallbackHandler__factory>;
    getContractFactory(
      name: "IPluginSetup",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPluginSetup__factory>;
    getContractFactory(
      name: "PluginSetup",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PluginSetup__factory>;
    getContractFactory(
      name: "IMajorityVoting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMajorityVoting__factory>;
    getContractFactory(
      name: "MajorityVotingBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MajorityVotingBase__factory>;
    getContractFactory(
      name: "Addresslist",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Addresslist__factory>;
    getContractFactory(
      name: "IERC1822ProxiableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1822ProxiableUpgradeable__factory>;
    getContractFactory(
      name: "IERC1967Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1967Upgradeable__factory>;
    getContractFactory(
      name: "IBeaconUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBeaconUpgradeable__factory>;
    getContractFactory(
      name: "ERC1967UpgradeUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1967UpgradeUpgradeable__factory>;
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "UUPSUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UUPSUpgradeable__factory>;
    getContractFactory(
      name: "IERC1155ReceiverUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155ReceiverUpgradeable__factory>;
    getContractFactory(
      name: "IERC1155Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Upgradeable__factory>;
    getContractFactory(
      name: "IERC20PermitUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20PermitUpgradeable__factory>;
    getContractFactory(
      name: "IERC20Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Upgradeable__factory>;
    getContractFactory(
      name: "IERC721ReceiverUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721ReceiverUpgradeable__factory>;
    getContractFactory(
      name: "ContextUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ContextUpgradeable__factory>;
    getContractFactory(
      name: "ERC165StorageUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165StorageUpgradeable__factory>;
    getContractFactory(
      name: "ERC165Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165Upgradeable__factory>;
    getContractFactory(
      name: "IERC165Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165Upgradeable__factory>;
    getContractFactory(
      name: "IERC1822Proxiable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1822Proxiable__factory>;
    getContractFactory(
      name: "IERC1271",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1271__factory>;
    getContractFactory(
      name: "IERC1967",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1967__factory>;
    getContractFactory(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBeacon__factory>;
    getContractFactory(
      name: "ERC1967Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1967Proxy__factory>;
    getContractFactory(
      name: "ERC1967Upgrade",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1967Upgrade__factory>;
    getContractFactory(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Proxy__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "AddresslistVoting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AddresslistVoting__factory>;
    getContractFactory(
      name: "AddresslistVotingSetup",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AddresslistVotingSetup__factory>;

    getContractAt(
      name: "DAO",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DAO>;
    getContractAt(
      name: "IDAO",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDAO>;
    getContractAt(
      name: "IEIP4824",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IEIP4824>;
    getContractAt(
      name: "IPermissionCondition",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IPermissionCondition>;
    getContractAt(
      name: "PermissionLib",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PermissionLib>;
    getContractAt(
      name: "PermissionManager",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PermissionManager>;
    getContractAt(
      name: "DaoAuthorizableUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DaoAuthorizableUpgradeable>;
    getContractAt(
      name: "IPlugin",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IPlugin>;
    getContractAt(
      name: "IMembership",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMembership>;
    getContractAt(
      name: "PluginUUPSUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PluginUUPSUpgradeable>;
    getContractAt(
      name: "IProposal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IProposal>;
    getContractAt(
      name: "ProposalUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ProposalUpgradeable>;
    getContractAt(
      name: "CallbackHandler",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CallbackHandler>;
    getContractAt(
      name: "IPluginSetup",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IPluginSetup>;
    getContractAt(
      name: "PluginSetup",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PluginSetup>;
    getContractAt(
      name: "IMajorityVoting",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMajorityVoting>;
    getContractAt(
      name: "MajorityVotingBase",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MajorityVotingBase>;
    getContractAt(
      name: "Addresslist",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Addresslist>;
    getContractAt(
      name: "IERC1822ProxiableUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1822ProxiableUpgradeable>;
    getContractAt(
      name: "IERC1967Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1967Upgradeable>;
    getContractAt(
      name: "IBeaconUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IBeaconUpgradeable>;
    getContractAt(
      name: "ERC1967UpgradeUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1967UpgradeUpgradeable>;
    getContractAt(
      name: "Initializable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "UUPSUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UUPSUpgradeable>;
    getContractAt(
      name: "IERC1155ReceiverUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155ReceiverUpgradeable>;
    getContractAt(
      name: "IERC1155Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Upgradeable>;
    getContractAt(
      name: "IERC20PermitUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20PermitUpgradeable>;
    getContractAt(
      name: "IERC20Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Upgradeable>;
    getContractAt(
      name: "IERC721ReceiverUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721ReceiverUpgradeable>;
    getContractAt(
      name: "ContextUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ContextUpgradeable>;
    getContractAt(
      name: "ERC165StorageUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165StorageUpgradeable>;
    getContractAt(
      name: "ERC165Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165Upgradeable>;
    getContractAt(
      name: "IERC165Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165Upgradeable>;
    getContractAt(
      name: "IERC1822Proxiable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1822Proxiable>;
    getContractAt(
      name: "IERC1271",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1271>;
    getContractAt(
      name: "IERC1967",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1967>;
    getContractAt(
      name: "IBeacon",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IBeacon>;
    getContractAt(
      name: "ERC1967Proxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1967Proxy>;
    getContractAt(
      name: "ERC1967Upgrade",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1967Upgrade>;
    getContractAt(
      name: "Proxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Proxy>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "AddresslistVoting",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AddresslistVoting>;
    getContractAt(
      name: "AddresslistVotingSetup",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AddresslistVotingSetup>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
