/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPluginSetup__factory } from "./IPluginSetup__factory";
export { PluginSetup__factory } from "./PluginSetup__factory";
