/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEIP4824,
  IEIP4824Interface,
} from "../../../../../@aragon/osx/core/dao/IEIP4824";

const _abi = [
  {
    inputs: [],
    name: "daoURI",
    outputs: [
      {
        internalType: "string",
        name: "_daoURI",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEIP4824__factory {
  static readonly abi = _abi;
  static createInterface(): IEIP4824Interface {
    return new utils.Interface(_abi) as IEIP4824Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEIP4824 {
    return new Contract(address, _abi, signerOrProvider) as IEIP4824;
  }
}
