/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as groupVotingSol from "./GroupVoting.sol";
export type { groupVotingSol };
import type * as groupVotingSetupSol from "./GroupVotingSetup.sol";
export type { groupVotingSetupSol };
